// frontend/nextjs/src/app/(protected)/admin/providers/page.tsx
"use client";

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { AddProviderModal } from '@/components/services/AddProviderModal';
import { PendingInterventions } from '@/components/services/PendingInterventions';
import { PlusCircle, AlertCircle } from 'lucide-react';

export default function ProviderManagementPage() {
  const [addModalOpen, setAddModalOpen] = useState(false);

  const handleProviderAdded = (scrapedDataId: string) => {
    console.log('Provider added:', scrapedDataId);
    // Optionally show a toast notification or refresh data
  };

  return (
    <div className="container mx-auto py-8 px-4">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-3xl font-bold">Provider Management</h1>
          <p className="text-muted-foreground mt-1">
            Add and manage service providers in the roster
          </p>
        </div>
        <Button onClick={() => setAddModalOpen(true)} size="lg">
          <PlusCircle className="mr-2 h-5 w-5" />
          Add Provider
        </Button>
      </div>

      <Tabs defaultValue="interventions" className="space-y-6">
        <TabsList>
          <TabsTrigger value="interventions" className="gap-2">
            <AlertCircle className="h-4 w-4" />
            Pending Interventions
          </TabsTrigger>
          <TabsTrigger value="recent">Recent Additions</TabsTrigger>
        </TabsList>

        <TabsContent value="interventions" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Review Required</CardTitle>
              <CardDescription>
                These providers need manual review to determine if they match existing records
              </CardDescription>
            </CardHeader>
            <CardContent>
              <PendingInterventions />
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="recent" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Recent Additions</CardTitle>
              <CardDescription>
                Recently added providers and their processing status
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Coming soon: View recently processed providers
              </p>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      <AddProviderModal
        open={addModalOpen}
        onOpenChange={setAddModalOpen}
        onSuccess={handleProviderAdded}
      />
    </div>
  );
}

// frontend/sveltekit/hestami-ai-ui/src/routes/staff/providers/+page.svelte
<script lang="ts">
  import AddProviderModal from '$lib/components/AddProviderModal.svelte';
  import PendingInterventions from '$lib/components/PendingInterventions.svelte';
  import { AlertCircle, PlusCircle, Search } from 'lucide-svelte';
  
  let addModalOpen = false;
  
  function handleProviderAdded(event: CustomEvent<{ id: string }>) {
    console.log('Provider added:', event.detail.id);
    // Optionally show a toast notification
  }
</script>

<svelte:head>
  <title>Provider Management - Hestami AI</title>
</svelte:head>

<div class="container mx-auto p-4 space-y-6">
  <!-- Header -->
  <div class="flex items-center justify-between">
    <div>
      <h1 class="h1">Provider Management</h1>
      <p class="text-surface-600-300-token mt-1">
        Add and manage service providers in the roster
      </p>
    </div>
    <div class="flex gap-3">
      <a href="/staff/providers/search" class="btn variant-ghost-surface">
        <Search class="h-5 w-5" />
        <span>Search Providers</span>
      </a>
      <button class="btn variant-filled-primary" on:click={() => addModalOpen = true}>
        <PlusCircle class="h-5 w-5" />
        <span>Add Provider</span>
      </button>
    </div>
  </div>
  
  <!-- Main Content Card -->
  <div class="card">
    <header class="card-header flex items-center gap-3">
      <AlertCircle class="h-6 w-6 text-warning-500" />
      <div>
        <h2 class="h3">Pending Interventions</h2>
        <p class="text-sm text-surface-600-300-token">
          These providers need manual review to determine if they match existing records
        </p>
      </div>
    </header>
    <section class="p-4">
      <PendingInterventions />
    </section>
  </div>
</div>

<AddProviderModal bind:open={addModalOpen} on:success={handleProviderAdded} />
