// frontend/sveltekit/hestami-ai-ui/src/routes/staff/requests/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import { format } from 'date-fns';
	import { Search, Filter, Bell, ChevronLeft, ChevronRight } from 'lucide-svelte';
	import type { ServiceRequest, QueueData } from '$lib/types';

	// Get data from page load
	const { data } = $props<{ data: any }>();
	
	// Reactive state for filters
	let searchQuery = $state(data.filters.search || '');
	let statusFilter = $state(data.filters.status || 'all');
	let priorityFilter = $state(data.filters.priority || 'all');
	let assignedToFilter = $state(data.filters.assigned_to || 'all');
	
	// Saved filters in localStorage
	let savedFilters = $state<{ name: string; filters: any }[]>([]);
	let showSaveFilterModal = $state(false);
	let newFilterName = $state('');
	
	// Load saved filters from localStorage on mount
	$effect(() => {
		if (typeof window !== 'undefined') {
			const saved = localStorage.getItem('staff_saved_filters');
			if (saved) {
				savedFilters = JSON.parse(saved);
			}
		}
	});
	
	// Apply filters to URL
	function applyFilters() {
		const params = new URLSearchParams();
		
		if (searchQuery) params.set('search', searchQuery);
		if (statusFilter !== 'all') params.set('status', statusFilter);
		if (priorityFilter !== 'all') params.set('priority', priorityFilter);
		if (assignedToFilter !== 'all') params.set('assigned_to', assignedToFilter);
		
		goto(`/staff/requests?${params.toString()}`);
	}
	
	// Save current filter set
	function saveCurrentFilters() {
		if (!newFilterName.trim()) return;
		
		const filterSet = {
			name: newFilterName,
			filters: {
				search: searchQuery,
				status: statusFilter,
				priority: priorityFilter,
				assigned_to: assignedToFilter
			}
		};
		
		savedFilters = [...savedFilters, filterSet];
		localStorage.setItem('staff_saved_filters', JSON.stringify(savedFilters));
		
		newFilterName = '';
		showSaveFilterModal = false;
	}
	
	// Load saved filter
	function loadSavedFilter(filterSet: any) {
		searchQuery = filterSet.filters.search || '';
		statusFilter = filterSet.filters.status || 'all';
		priorityFilter = filterSet.filters.priority || 'all';
		assignedToFilter = filterSet.filters.assigned_to || 'all';
		applyFilters();
	}
	
	// Delete saved filter
	function deleteSavedFilter(index: number) {
		savedFilters = savedFilters.filter((_, i) => i !== index);
		localStorage.setItem('staff_saved_filters', JSON.stringify(savedFilters));
	}
	
	// Clear all filters
	function clearFilters() {
		searchQuery = '';
		statusFilter = 'all';
		priorityFilter = 'all';
		assignedToFilter = 'all';
		goto('/staff/requests');
	}
	
	// Pagination
	function goToPage(pageNum: number) {
		const params = new URLSearchParams($page.url.searchParams);
		params.set('page', pageNum.toString());
		goto(`/staff/requests?${params.toString()}`);
	}
	
	// Format helpers
	function formatDate(dateString: string): string {
		return format(new Date(dateString), 'MMM d, yyyy');
	}
	
	function formatStatus(status: string): string {
		return status.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
	}
	
	function getStatusClass(status: string): string {
		switch (status.toLowerCase()) {
			case 'pending': return 'badge variant-soft-warning';
			case 'in_research': return 'badge variant-soft-secondary';
			case 'bidding': return 'badge variant-soft-primary';
			case 'accepted': return 'badge variant-soft-success';
			case 'scheduled': return 'badge variant-soft-tertiary';
			case 'in_progress': return 'badge variant-soft-tertiary';
			case 'completed': return 'badge variant-soft-success';
			case 'cancelled': return 'badge variant-soft-error';
			default: return 'badge variant-soft-surface';
		}
	}
	
	function getPriorityClass(priority: string): string {
		switch (priority.toLowerCase()) {
			case 'urgent': return 'badge variant-filled-error';
			case 'high': return 'badge variant-filled-warning';
			case 'medium': return 'badge variant-soft-secondary';
			case 'low': return 'badge variant-soft-surface';
			default: return 'badge variant-soft-surface';
		}
	}
	
	function getPriorityEmoji(priority: string): string {
		switch (priority.toLowerCase()) {
			case 'urgent': return '🔴';
			case 'high': return '🟠';
			case 'medium': return '🟢';
			case 'low': return '⚪';
			default: return '';
		}
	}
</script>

<div class="container mx-auto p-6 space-y-6">
	<!-- Header -->
	<header class="flex justify-between items-center">
		<div>
			<h1 class="h2">Service Queue</h1>
			<p class="text-surface-600-300-token">Manage and triage service requests</p>
		</div>
		<div class="flex gap-2">
			<button class="btn variant-ghost-surface" onclick={() => (showSaveFilterModal = true)}>
				Save Current Filters
			</button>
		</div>
	</header>
	
	<!-- Queue Stats -->
	{#if data.queueStats}
		<div class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-8 gap-4">
			<div class="card p-4 text-center">
				<div class="text-2xl font-bold">{data.queueStats.queue_counts?.total || 0}</div>
				<div class="text-sm text-surface-600-300-token">Total</div>
			</div>
			<div class="card p-4 text-center">
				<div class="text-2xl font-bold text-warning-500">{data.queueStats.queue_counts?.pending || 0}</div>
				<div class="text-sm text-surface-600-300-token">Pending</div>
			</div>
			<div class="card p-4 text-center">
				<div class="text-2xl font-bold text-secondary-500">{data.queueStats.queue_counts?.in_research || 0}</div>
				<div class="text-sm text-surface-600-300-token">In Research</div>
			</div>
			<div class="card p-4 text-center">
				<div class="text-2xl font-bold text-primary-500">{data.queueStats.queue_counts?.bidding || 0}</div>
				<div class="text-sm text-surface-600-300-token">Bidding</div>
			</div>
			<div class="card p-4 text-center">
				<div class="text-2xl font-bold text-success-500">{data.queueStats.queue_counts?.accepted || 0}</div>
				<div class="text-sm text-surface-600-300-token">Accepted</div>
			</div>
			<div class="card p-4 text-center">
				<div class="text-2xl font-bold text-tertiary-500">{data.queueStats.queue_counts?.scheduled || 0}</div>
				<div class="text-sm text-surface-600-300-token">Scheduled</div>
			</div>
			<div class="card p-4 text-center">
				<div class="text-2xl font-bold text-error-500">{data.queueStats.sla_indicators?.overdue || 0}</div>
				<div class="text-sm text-surface-600-300-token">Overdue</div>
			</div>
			<div class="card p-4 text-center">
				<div class="text-2xl font-bold text-warning-500">{data.queueStats.sla_indicators?.approaching_deadline || 0}</div>
				<div class="text-sm text-surface-600-300-token">Due Soon</div>
			</div>
		</div>
	{/if}
	
	<!-- Filters -->
	<div class="card p-4">
		<div class="space-y-4">
			<!-- Search -->
			<div class="input-group input-group-divider grid-cols-[auto_1fr_auto]">
				<div class="input-group-shim flex items-center justify-center">
					<Search class="h-4 w-4" />
				</div>
				<input
					type="text"
					placeholder="Search by request title, property, or customer..."
					bind:value={searchQuery}
					onkeydown={(e) => e.key === 'Enter' && applyFilters()}
					class="input"
				/>
			</div>
			
			<!-- Filter Dropdowns -->
			<div class="flex flex-wrap gap-2">
				<select bind:value={statusFilter} onchange={applyFilters} class="select">
					<option value="all">All Statuses</option>
					<option value="PENDING">Pending</option>
					<option value="IN_RESEARCH">In Research</option>
					<option value="BIDDING">Bidding</option>
					<option value="ACCEPTED">Accepted</option>
					<option value="SCHEDULED">Scheduled</option>
					<option value="IN_PROGRESS">In Progress</option>
					<option value="COMPLETED">Completed</option>
					<option value="CANCELLED">Cancelled</option>
				</select>
				
				<select bind:value={priorityFilter} onchange={applyFilters} class="select">
					<option value="all">All Priorities</option>
					<option value="URGENT">Urgent</option>
					<option value="HIGH">High</option>
					<option value="MEDIUM">Medium</option>
					<option value="LOW">Low</option>
				</select>
				
				<select bind:value={assignedToFilter} onchange={applyFilters} class="select">
					<option value="all">All Assignments</option>
					<option value="me">My Queue</option>
					<option value="unassigned">Unassigned</option>
				</select>
				
				{#if searchQuery || statusFilter !== 'all' || priorityFilter !== 'all' || assignedToFilter !== 'all'}
					<button class="btn variant-ghost-surface" onclick={clearFilters}>
						Clear Filters
					</button>
				{/if}
			</div>
			
			<!-- Saved Filters -->
			{#if savedFilters.length > 0}
				<div class="flex flex-wrap gap-2">
					<span class="text-sm font-semibold">Saved Filters:</span>
					{#each savedFilters as filter, i}
						<div class="chip variant-soft-primary flex items-center gap-2">
							<button
								class="flex-1"
								onclick={() => loadSavedFilter(filter)}
							>
								{filter.name}
							</button>
							<span
								class="cursor-pointer text-error-500 hover:text-error-600"
								onclick={(e) => {
									e.stopPropagation();
									deleteSavedFilter(i);
								}}
								role="button"
								tabindex="0"
							>
								×
							</span>
						</div>
					{/each}
				</div>
			{/if}
		</div>
	</div>
	
	<!-- Service Requests Table -->
	<div class="card">
		<div class="table-container">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Priority</th>
						<th>Request Title</th>
						<th>Property / Owner</th>
						<th>Status</th>
						<th>Assigned To</th>
						<th>Created</th>
						<th class="text-right">Actions</th>
					</tr>
				</thead>
				<tbody>
					{#if data.serviceRequests.length === 0}
						<tr>
							<td colspan="7" class="text-center py-8">
								No service requests found matching your filters.
							</td>
						</tr>
					{:else}
						{#each data.serviceRequests as request}
							<tr>
								<td>
									<span class="{getPriorityClass(request.priority)}">
										{getPriorityEmoji(request.priority)} {request.priority}
									</span>
								</td>
								<td>
									<div class="font-semibold">{request.title}</div>
									<div class="text-xs text-surface-600-300-token">{request.category_display}</div>
								</td>
								<td>
									<div class="font-medium">
										{request.property_details.address}
									</div>
									<div class="text-xs text-surface-600-300-token">
										{request.created_by_details.first_name} {request.created_by_details.last_name}
									</div>
								</td>
								<td>
									<span class="{getStatusClass(request.status)}">
										{formatStatus(request.status)}
									</span>
								</td>
								<td>
									{#if request.assigned_to_details}
										<div class="text-sm">
											{request.assigned_to_details.first_name} {request.assigned_to_details.last_name}
										</div>
									{:else}
										<span class="text-surface-500-400-token text-sm">Unassigned</span>
									{/if}
								</td>
								<td class="text-sm">{formatDate(request.created_at)}</td>
								<td class="text-right">
									<a href="/staff/requests/{request.id}" class="btn btn-sm variant-ghost-primary">
										View
									</a>
								</td>
							</tr>
						{/each}
					{/if}
				</tbody>
			</table>
		</div>
		
		<!-- Pagination -->
		{#if data.pagination.count > 0}
			<div class="p-4 flex justify-between items-center border-t border-surface-300-600-token">
				<div class="text-sm text-surface-600-300-token">
					Showing page {data.pagination.currentPage} of {Math.ceil(data.pagination.count / 20)}
					({data.pagination.count} total requests)
				</div>
				<div class="flex gap-2">
					<button
						class="btn btn-sm variant-ghost-surface"
						disabled={!data.pagination.previous}
						onclick={() => goToPage(data.pagination.currentPage - 1)}
					>
						<ChevronLeft class="h-4 w-4" />
						Previous
					</button>
					<button
						class="btn btn-sm variant-ghost-surface"
						disabled={!data.pagination.next}
						onclick={() => goToPage(data.pagination.currentPage + 1)}
					>
						Next
						<ChevronRight class="h-4 w-4" />
					</button>
				</div>
			</div>
		{/if}
	</div>
</div>

<!-- Save Filter Modal -->
{#if showSaveFilterModal}
	<div class="modal-backdrop" onclick={() => (showSaveFilterModal = false)}>
		<div class="modal card p-6 w-full max-w-md" onclick={(e) => e.stopPropagation()}>
			<h3 class="h3 mb-4">Save Current Filters</h3>
			<input
				type="text"
				placeholder="Filter name (e.g., 'Urgent Unassigned')"
				bind:value={newFilterName}
				class="input mb-4"
			/>
			<div class="flex gap-2 justify-end">
				<button class="btn variant-ghost-surface" onclick={() => (showSaveFilterModal = false)}>
					Cancel
				</button>
				<button class="btn variant-filled-primary" onclick={saveCurrentFilters}>
					Save
				</button>
			</div>
		</div>
	</div>
{/if}

<style>
	.modal-backdrop {
		position: fixed;
		top: 0;
		left: 0;
		right: 0;
		bottom: 0;
		background: rgba(0, 0, 0, 0.5);
		display: flex;
		align-items: center;
		justify-content: center;
		z-index: 1000;
	}
	
	.modal {
		max-height: 90vh;
		overflow-y: auto;
	}
</style>

// frontend/nextjs/src/app/(protected)/admin/requests/page.tsx
'use client';

import { useSession } from 'next-auth/react';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Navbar from '@/components/Navbar';
import { useThemeMode } from '@/hooks/useThemeMode';
import { format } from 'date-fns';

// Types
interface ServiceRequest {
  id: string;
  title: string;
  status: string;
  created_at: string;
  property_details: {
    address: string;
    city: string;
    state: string;
    zip_code: string;
  };
  category_display: string;
  created_by_details: {
    name: string;
    email: string;
  };
}

// Filter types
interface Filters {
  status: string;
  category: string;
  startDate: string;
  endDate: string;
  location: string;
}

export default function AdminRequests() {
  const { data: session } = useSession({
    required: true,
    onUnauthenticated() {
      window.location.href = '/login';
    },
  });
  const { mounted } = useThemeMode();
  const router = useRouter();
  const [requests, setRequests] = useState<ServiceRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState<Filters>({
    status: '',
    category: '',
    startDate: '',
    endDate: '',
    location: '',
  });
  const [categories, setCategories] = useState<{ value: string; label: string }[]>([]);
  const [statuses, setStatuses] = useState<{ value: string; label: string }[]>([
    { value: 'PENDING', label: 'Pending' },
    { value: 'IN_RESEARCH', label: 'In Research' },
    { value: 'BIDDING', label: 'Open for Bidding' },
    { value: 'REOPENED_BIDDING', label: 'Reopened for Bidding' },
    { value: 'ACCEPTED', label: 'Accepted' },
    { value: 'SCHEDULED', label: 'Scheduled' },
    { value: 'IN_PROGRESS', label: 'In Progress' },
    { value: 'COMPLETED', label: 'Completed' },
    { value: 'CANCELLED', label: 'Cancelled' },
    { value: 'DECLINED', label: 'Declined' },
  ]);

  // Fetch service requests
  useEffect(() => {
    const fetchRequests = async () => {
      if (!session?.user) return;
      
      try {
        setLoading(true);
        
        // Build query params
        const params = new URLSearchParams();
        if (filters.status) params.append('status', filters.status);
        if (filters.category) params.append('category', filters.category);
        if (filters.startDate) params.append('start_date', filters.startDate);
        if (filters.endDate) params.append('end_date', filters.endDate);
        if (filters.location) params.append('location', filters.location);
        
        const queryString = params.toString() ? `?${params.toString()}` : '';
        
        const response = await fetch(`/api/services/requests${queryString}`, {
          headers: {
            Authorization: `Bearer ${session.user.accessToken}`,
          },
        });
        
        if (response.ok) {
          const data = await response.json();
          setRequests(data);
        } else {
          console.error('Failed to fetch service requests');
        }
      } catch (error) {
        console.error('Error fetching service requests:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchRequests();
  }, [session, filters]);

  // Fetch categories
  useEffect(() => {
    const fetchCategories = async () => {
      if (!session?.user) return;
      
      try {
        const response = await fetch('/api/services/categories', {
          headers: {
            Authorization: `Bearer ${session.user.accessToken}`,
          },
        });
        
        if (response.ok) {
          const data = await response.json();
          const formattedCategories = data.map((cat: any) => ({
            value: cat.id,
            label: cat.name,
          }));
          setCategories(formattedCategories);
        }
      } catch (error) {
        console.error('Error fetching categories:', error);
      }
    };

    fetchCategories();
  }, [session]);

  // Handle filter changes
  const handleFilterChange = (name: keyof Filters, value: string) => {
    setFilters(prev => ({ ...prev, [name]: value }));
  };

  // Handle view request details
  const handleViewRequest = (id: string) => {
    router.push(`/admin/requests/${id}`);
  };

  // Prevent hydration mismatch
  if (!mounted || !session?.user) {
    return null;
  }

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <Navbar />
      <main className="py-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center">
            <h1 className="text-3xl font-bold text-gray-900 dark:text-white">
              Service Requests
            </h1>
          </div>
          
          {/* Filters */}
          <div className="mt-6 bg-white dark:bg-gray-800 shadow px-4 py-5 sm:rounded-lg sm:p-6">
            <div className="md:grid md:grid-cols-5 md:gap-6">
              <div className="md:col-span-1">
                <h3 className="text-lg font-medium leading-6 text-gray-900 dark:text-white">Filters</h3>
                <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                  Filter service requests by various criteria.
                </p>
              </div>
              <div className="mt-5 md:mt-0 md:col-span-4">
                <div className="grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-2 lg:grid-cols-3">
                  {/* Status Filter */}
                  <div>
                    <label htmlFor="status" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                      Status
                    </label>
                    <select
                      id="status"
                      name="status"
                      className="mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-primary-main focus:border-primary-main sm:text-sm rounded-md dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                      value={filters.status}
                      onChange={(e) => handleFilterChange('status', e.target.value)}
                    >
                      <option value="">All Statuses</option>
                      {statuses.map((status) => (
                        <option key={status.value} value={status.value}>
                          {status.label}
                        </option>
                      ))}
                    </select>
                  </div>
                  
                  {/* Category Filter */}
                  <div>
                    <label htmlFor="category" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                      Category
                    </label>
                    <select
                      id="category"
                      name="category"
                      className="mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-primary-main focus:border-primary-main sm:text-sm rounded-md dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                      value={filters.category}
                      onChange={(e) => handleFilterChange('category', e.target.value)}
                    >
                      <option value="">All Categories</option>
                      {categories.map((category) => (
                        <option key={category.value} value={category.value}>
                          {category.label}
                        </option>
                      ))}
                    </select>
                  </div>
                  
                  {/* Location Filter */}
                  <div>
                    <label htmlFor="location" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                      Location
                    </label>
                    <input
                      type="text"
                      name="location"
                      id="location"
                      className="mt-1 focus:ring-primary-main focus:border-primary-main block w-full shadow-sm sm:text-sm border-gray-300 rounded-md dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                      placeholder="City, State, or ZIP"
                      value={filters.location}
                      onChange={(e) => handleFilterChange('location', e.target.value)}
                    />
                  </div>
                  
                  {/* Date Range Filters */}
                  <div>
                    <label htmlFor="startDate" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                      Start Date
                    </label>
                    <input
                      type="date"
                      name="startDate"
                      id="startDate"
                      className="mt-1 focus:ring-primary-main focus:border-primary-main block w-full shadow-sm sm:text-sm border-gray-300 rounded-md dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                      value={filters.startDate}
                      onChange={(e) => handleFilterChange('startDate', e.target.value)}
                    />
                  </div>
                  
                  <div>
                    <label htmlFor="endDate" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                      End Date
                    </label>
                    <input
                      type="date"
                      name="endDate"
                      id="endDate"
                      className="mt-1 focus:ring-primary-main focus:border-primary-main block w-full shadow-sm sm:text-sm border-gray-300 rounded-md dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                      value={filters.endDate}
                      onChange={(e) => handleFilterChange('endDate', e.target.value)}
                    />
                  </div>
                  
                  {/* Clear Filters Button */}
                  <div className="flex items-end">
                    <button
                      type="button"
                      className="inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-main dark:bg-gray-700 dark:text-white dark:border-gray-600 dark:hover:bg-gray-600"
                      onClick={() => setFilters({
                        status: '',
                        category: '',
                        startDate: '',
                        endDate: '',
                        location: '',
                      })}
                    >
                      Clear Filters
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          
          {/* Service Requests Table */}
          <div className="mt-8 flex flex-col">
            <div className="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
              <div className="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div className="shadow overflow-hidden border-b border-gray-200 dark:border-gray-700 sm:rounded-lg">
                  <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                    <thead className="bg-gray-50 dark:bg-gray-800">
                      <tr>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                          Title
                        </th>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                          Status
                        </th>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                          Category
                        </th>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                          Location
                        </th>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                          Created By
                        </th>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                          Date
                        </th>
                        <th scope="col" className="relative px-6 py-3">
                          <span className="sr-only">Actions</span>
                        </th>
                      </tr>
                    </thead>
                    <tbody className="bg-white dark:bg-gray-900 divide-y divide-gray-200 dark:divide-gray-700">
                      {loading ? (
                        <tr>
                          <td colSpan={7} className="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-500 dark:text-gray-400">
                            Loading...
                          </td>
                        </tr>
                      ) : requests.length === 0 ? (
                        <tr>
                          <td colSpan={7} className="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-500 dark:text-gray-400">
                            No service requests found
                          </td>
                        </tr>
                      ) : (
                        requests.map((request) => (
                          <tr 
                            key={request.id} 
                            className="hover:bg-gray-50 dark:hover:bg-gray-800 cursor-pointer"
                            onClick={() => handleViewRequest(request.id)}
                          >
                            <td className="px-6 py-4 whitespace-nowrap">
                              <div className="text-sm font-medium text-gray-900 dark:text-white">
                                {request.title}
                              </div>
                            </td>
                            <td className="px-6 py-4 whitespace-nowrap">
                              <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${
                                request.status === 'PENDING' ? 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200' :
                                request.status === 'IN_RESEARCH' ? 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200' :
                                request.status === 'BIDDING' ? 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200' :
                                request.status === 'SCHEDULED' ? 'bg-indigo-100 text-indigo-800 dark:bg-indigo-900 dark:text-indigo-200' :
                                request.status === 'IN_PROGRESS' ? 'bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200' :
                                request.status === 'COMPLETED' ? 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200' :
                                request.status === 'CANCELLED' ? 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200' :
                                'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-200'
                              }`}>
                                {request.status.replace(/_/g, ' ')}
                              </span>
                            </td>
                            <td className="px-6 py-4 whitespace-nowrap">
                              <div className="text-sm text-gray-500 dark:text-gray-400">
                                {request.category_display}
                              </div>
                            </td>
                            <td className="px-6 py-4 whitespace-nowrap">
                              <div className="text-sm text-gray-500 dark:text-gray-400">
                                {request.property_details?.city}, {request.property_details?.state}
                              </div>
                            </td>
                            <td className="px-6 py-4 whitespace-nowrap">
                              <div className="text-sm text-gray-500 dark:text-gray-400">
                                {request.created_by_details?.name}
                              </div>
                            </td>
                            <td className="px-6 py-4 whitespace-nowrap">
                              <div className="text-sm text-gray-500 dark:text-gray-400">
                                {format(new Date(request.created_at), 'MMM d, yyyy')}
                              </div>
                            </td>
                            <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                              <button
                                onClick={(e) => {
                                  e.stopPropagation();
                                  handleViewRequest(request.id);
                                }}
                                className="text-primary-main hover:text-primary-dark"
                              >
                                View
                              </button>
                            </td>
                          </tr>
                        ))
                      )}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
