// frontend/nextjs/src/components/services/AddProviderModal.tsx
"use client";

import React, { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Loader2, CheckCircle2, AlertCircle } from 'lucide-react';

interface AddProviderModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSuccess?: (scrapedDataId: string) => void;
}

interface FormData {
  source_name: string;
  source_url: string;
  raw_html: string;
  notes: string;
}

export function AddProviderModal({ open, onOpenChange, onSuccess }: AddProviderModalProps) {
  const [formData, setFormData] = useState<FormData>({
    source_name: '',
    source_url: '',
    raw_html: '',
    notes: ''
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setSuccess(false);

    try {
      const response = await fetch('/api/services/providers/add-to-roster/', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to add provider');
      }

      const data = await response.json();
      setSuccess(true);
      
      // Reset form
      setFormData({
        source_name: '',
        source_url: '',
        raw_html: '',
        notes: ''
      });

      // Call success callback
      if (onSuccess) {
        onSuccess(data.id);
      }

      // Close modal after 2 seconds
      setTimeout(() => {
        onOpenChange(false);
        setSuccess(false);
      }, 2000);

    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (field: keyof FormData, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <DialogTitle>Add Provider to Roster</DialogTitle>
          <DialogDescription>
            Add a service provider from an external source. The system will automatically extract and process the provider information.
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4">
          {/* Source Name */}
          <div className="space-y-2">
            <Label htmlFor="source_name">Source Name *</Label>
            <Input
              id="source_name"
              placeholder="e.g., Yelp, Angi, Google"
              value={formData.source_name}
              onChange={(e) => handleChange('source_name', e.target.value)}
              required
              disabled={loading}
            />
          </div>

          {/* Source URL */}
          <div className="space-y-2">
            <Label htmlFor="source_url">Source URL *</Label>
            <Input
              id="source_url"
              type="url"
              placeholder="https://www.yelp.com/biz/acme-hvac"
              value={formData.source_url}
              onChange={(e) => handleChange('source_url', e.target.value)}
              required
              disabled={loading}
            />
          </div>

          {/* Raw HTML (Optional) */}
          <div className="space-y-2">
            <Label htmlFor="raw_html">Raw HTML (Optional)</Label>
            <Textarea
              id="raw_html"
              placeholder="Paste the HTML content here if available..."
              value={formData.raw_html}
              onChange={(e) => handleChange('raw_html', e.target.value)}
              rows={4}
              disabled={loading}
              className="font-mono text-sm"
            />
            <p className="text-xs text-muted-foreground">
              Leave empty to fetch automatically from the URL
            </p>
          </div>

          {/* Notes */}
          <div className="space-y-2">
            <Label htmlFor="notes">Notes (Optional)</Label>
            <Textarea
              id="notes"
              placeholder="Add any additional notes or context..."
              value={formData.notes}
              onChange={(e) => handleChange('notes', e.target.value)}
              rows={2}
              disabled={loading}
            />
          </div>

          {/* Error Alert */}
          {error && (
            <Alert variant="destructive">
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}

          {/* Success Alert */}
          {success && (
            <Alert className="border-green-500 bg-green-50">
              <CheckCircle2 className="h-4 w-4 text-green-600" />
              <AlertDescription className="text-green-600">
                Provider added successfully! Processing will begin shortly.
              </AlertDescription>
            </Alert>
          )}

          {/* Action Buttons */}
          <div className="flex justify-end gap-3 pt-4">
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={loading}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              disabled={loading || success}
            >
              {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
              {loading ? 'Adding...' : 'Add Provider'}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
}

// frontend/sveltekit/hestami-ai-ui/src/lib/components/AddProviderModal.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { X, AlertCircle, CheckCircle2 } from 'lucide-svelte';
  import RichTextEditor from '$lib/components/RichTextEditor.svelte';
  
  export let open = false;
  
  const dispatch = createEventDispatcher();
  
  let formData = {
    source_url: '',
    raw_html: '',
    raw_text: '',
    notes: ''
  };
  
  let loading = false;
  let error: string | null = null;
  let success = false;
  
  async function handleSubmit() {
    loading = true;
    error = null;
    success = false;
    
    try {
      const response = await fetch('/api/services/providers/add-to-roster/', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      });
      
      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to add provider');
      }
      
      const data = await response.json();
      success = true;
      
      // Reset form
      formData = {
        source_url: '',
        raw_html: '',
        raw_text: '',
        notes: ''
      };
      
      // Dispatch success event
      dispatch('success', { id: data.id });
      
      // Close modal after 2 seconds
      setTimeout(() => {
        open = false;
        success = false;
      }, 2000);
      
    } catch (err) {
      error = err instanceof Error ? err.message : 'An error occurred';
    } finally {
      loading = false;
    }
  }
  
  function handleClose() {
    if (!loading) {
      open = false;
      error = null;
      success = false;
    }
  }
</script>

{#if open}
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <div class="modal-backdrop backdrop-blur-sm bg-surface-backdrop-token" role="presentation" on:click={handleClose} on:keydown={(e) => e.key === 'Escape' && handleClose()}>
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <div class="modal card variant-filled-surface p-0 w-full max-w-2xl max-h-[90vh] overflow-y-auto" role="dialog" aria-modal="true" tabindex="-1" on:click|stopPropagation on:keydown|stopPropagation>
      <header class="card-header flex items-center justify-between">
        <div>
          <h2 class="h3">Add Provider to Roster</h2>
          <p class="text-sm text-surface-600-300-token mt-1">
            Add a service provider from an external source. The system will automatically extract and process the provider information.
          </p>
        </div>
        <button type="button" class="btn-icon variant-ghost-surface" on:click={handleClose} disabled={loading}>
          <X class="h-5 w-5" />
        </button>
      </header>
      
      <form on:submit|preventDefault={handleSubmit} class="p-6 space-y-4">
        <!-- Source URL -->
        <label class="label">
          <span class="font-semibold">Source URL *</span>
          <input
            type="url"
            class="input"
            placeholder="https://www.yelp.com/biz/acme-hvac"
            bind:value={formData.source_url}
            required
            disabled={loading}
          />
        </label>
        
        <!-- Rich Content -->
        <div class="space-y-2">
          <!-- svelte-ignore a11y_label_has_associated_control -->
          <label class="label">
            <span class="font-semibold">Rich Content</span>
          </label>
          <div class="rich-editor-container">
            <RichTextEditor 
              bind:value={formData.raw_html} 
              placeholder="Paste formatted content from web page..."
            />
          </div>
          <p class="text-xs text-surface-600-300-token">Paste content with formatting preserved. Leave empty to fetch automatically from the URL.</p>
        </div>
        
        <!-- Raw Text -->
        <label class="label">
          <span class="font-semibold">Raw Text</span>
          <textarea
            class="textarea"
            placeholder="Paste plain text content here..."
            bind:value={formData.raw_text}
            rows="3"
            disabled={loading}
          ></textarea>
          <p class="text-xs text-surface-600-300-token mt-1">Plain text version of the provider information</p>
        </label>
        
        <!-- Notes -->
        <label class="label">
          <span class="font-semibold">Notes (Optional)</span>
          <textarea
            class="textarea"
            placeholder="Add any additional notes or context..."
            bind:value={formData.notes}
            rows="2"
            disabled={loading}
          ></textarea>
        </label>
        
        <!-- Error Alert -->
        {#if error}
          <aside class="alert variant-filled-error">
            <AlertCircle class="h-5 w-5" />
            <div class="alert-message">
              <p>{error}</p>
            </div>
          </aside>
        {/if}
        
        <!-- Success Alert -->
        {#if success}
          <aside class="alert variant-filled-success">
            <CheckCircle2 class="h-5 w-5" />
            <div class="alert-message">
              <p>Provider added successfully! Processing will begin shortly.</p>
            </div>
          </aside>
        {/if}
        
        <!-- Action Buttons -->
        <footer class="flex gap-3 justify-end pt-4">
          <button
            type="button"
            class="btn variant-ghost-surface"
            on:click={handleClose}
            disabled={loading}
          >
            Cancel
          </button>
          <button
            type="submit"
            class="btn variant-filled-primary"
            disabled={loading || success}
          >
            {#if loading}
              <span class="animate-spin">⏳</span>
              <span>Adding...</span>
            {:else}
              <span>Add Provider</span>
            {/if}
          </button>
        </footer>
      </form>
    </div>
  </div>
{/if}

<style>
  .modal-backdrop {
    position: fixed;
    inset: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 50;
    padding: 1rem;
  }
  
  .modal {
    box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.3);
  }
  
  .rich-editor-container {
    max-height: 300px;
    overflow-y: auto;
    border: 1px solid rgb(var(--color-surface-400));
    border-radius: 0.375rem;
  }
  
  .rich-editor-container :global(.ProseMirror) {
    min-height: 150px;
    max-height: 280px;
    overflow-y: auto;
  }
</style>
